packages:
  - packages/*
  - examples/*
  - configs
  - scripts
  - tests
catalog:
  '@antfu/eslint-config': ^6.4.1
  '@eslint-react/eslint-plugin': ^2.3.12
  '@types/node': ^24.10.1
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.12
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^7.2.6
  vitest: ^4.0.15
