shellEmulator: true
catalogMode: prefer
cleanupUnusedCatalogs: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - configs
  - scripts
  - tests
catalog:
  '@antfu/eslint-config': ^6.4.1
  '@eslint-react/eslint-plugin': ^2.3.12
  '@types/node': ^24.10.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.0
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-react-swc': ^4.2.2
  "@vitejs/plugin-vue": ^6.0.2
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.12
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.9.1
  "@testing-library/react": ^15.0.7
  '@testing-library/user-event': ^14.5.2
  '@testing-library/vue': ^8.1.0
  jiti: ^2.6.1
  jsdom: ^27.2.0
  react: ^18.3.1
  'react-dom': ^18.3.1
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^7.2.6
  vitest: ^4.0.15
  vue: ^3.5.12
  vue-tsc: ^3.1.2
  '@vue/compiler-sfc': ^3.5.12
overrides:
  react: 18.3.1
  react-dom: 18.3.1
